# %% [markdown]
# This is `main.py`, the which have the main function of the program. The objective of this problem is to gather data, train and test financial ML models.
import requests as rq
import browser_cookie3
import pandas as pd
cookies = browser_cookie3.chromium()
headers = {
            'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7'
}
from data_retrieval import get_all_stock_data
from get_other_data import get_stocks_from_index

def get_all_nse_stocks():
    filepath = 'data/EQUITY_L.csv'
    stocks_df = pd.read_csv(filepath) 
    stocklist = stocks_df['SYMBOL'].tolist()
    return stocklist

# %%
def main():
    #index = 'NIFTY 500'
    #exclude_list = ['Non Banking Financial Company (NBFC)', 'Private Sector Bank', 'Public Sector Bank', 'Other Bank']
    #stock_list = get_stocks_from_index(index, headers, cookies, exclude=exclude_list, number_of_stocks=500)
    #print(stock_list)
    #stock_list = ['DCMSHRIRAM', 'ELGIEQUIP', 'GRSE', 'KNRCON', 'PTCIL', 'IFCI', 'ZENTEC', 'DATAPATTNS', 'TATACONSUM', 'KPITTECH', 'AFFLE', 'ABFRL', 'MCX', 'INOXINDIA', 'CAPLIPOINT', 'CAMS', 'COCHINSHIP', 'APARINDS', 'IGIL', 'NETWEB', 'SUMICHEM', 'KALYANKJIL', 'WELSPUNLIV', 'DEEPAKNTR', 'CAMPUS', 'CREDITACC', 'SONATSOFTW', 'NETWORK18', 'DEEPAKFERT', 'MINDACORP', 'TATACHEM', 'KIRLOSENG', 'RAMCOCEM', 'KIRLOSBROS', 'COROMANDEL', 'BEL', 'FSL', 'ACE', 'JBMA', 'INDGN', 'NAVINFLUOR', 'LLOYDSME', 'SAILIFE', 'ZENSARTECH', 'DALBHARAT', 'GRAPHITE', 'UTIAMC', 'VBL', 'KFINTECH', 'JSWHL', 'VTL', 'TRIVENI', 'HYUNDAI', 'KANSAINER', 'NAUKRI', 'SCHAEFFLER', 'MRPL', 'RPOWER', 'GVT&D', 'PNCINFRA', 'SWANCORP', 'CLEAN', 'BPCL', 'ASHOKLEY', 'MAZDOCK', 'SAGILITY', 'RVNL', 'BEML', 'KPRMILL', 'HEG', 'INDIACEM', 'AMBUJACEM', 'PIIND', 'ASAHIINDIA', 'IRB', 'JYOTICNC', 'DBREALTY', 'OLECTRA', 'MARUTI', 'BALKRISIND', 'DELHIVERY', 'JKCEMENT', 'TANLA', 'HONAUT', 'JWL', 'PRESTIGE', 'CHAMBLFERT', 'NAM-INDIA', 'ULTRACEMCO', 'KAYNES', 'BDL', 'BBTC', 'GODREJPROP', 'NH', 'GRANULES', 'PNBHOUSING', 'OIL', 'TRENT', 'TECHM', 'CASTROLIND', 'GODREJCP', 'RHIM', 'LTF', '360ONE', 'PFIZER', 'BLS', 'BLUESTARCO', 'HAL', 'GPIL', 'LTFOODS', 'ATUL', 'WAAREEENER', 'SOLARINDS', 'TCS', 'COALINDIA', 'RECLTD', 'ASTRAZEN', 'OBEROIRLTY', 'PERSISTENT', 'ANGELONE', 'GRAVITA', 'HINDPETRO', 'SOBHA', 'GODIGIT', 'IRCON', 'MPHASIS', 'LTIM', 'BSOFT', 'MEDANTA', 'TATAMOTORS', 'BAJAJHLDNG', 'IREDA', 'MANYAVAR', 'RAILTEL', 'GRASIM', 'JSWINFRA', 'CHOLAHLDNG', 'ONGC', 'M&M', 'IEX', 'COFORGE', 'POWERINDIA', 'BHEL', 'TRIDENT', 'NATCOPHARM', 'ALKYLAMINE', 'HSCL', 'TARIL', 'JSL', 'ABB', 'INFY', 'UNITDSPR', 'MAPMYINDIA', 'GMDCLTD', 'GILLETTE', 'SUNPHARMA', 'HEROMOTOCO', 'CERA', 'CONCORDBIO', 'EIDPARRY', 'SCHNEIDER', 'SWSOLAR', 'ELECON', 'SHREECEM', 'ZEEL', 'JBCHEPHARM', 'PFC', 'ECLERX', 'DOMS', 'IOC', 'AEGISLOG', 'RELIANCE', 'ASIANPAINT', 'SWIGGY', 'POLYMED', 'CRAFTSMAN', 'FINCABLES', 'PETRONET', 'BSE', 'DMART', 'EIHOTEL', 'SUZLON', 'RADICO', 'HDFCAMC', 'IRCTC', 'SUNTV', 'TEJASNET', 'CRISIL', 'LT', 'RTNINDIA', 'TITAGARH', 'LICI', 'CANFINHOME', 'LTTS', 'ALOKINDS', 'TORNTPHARM', 'SONACOMS', 'ABREL', 'TORNTPOWER', 'APLLTD', 'TATATECH', 'SCI', 'REDINGTON', 'LODHA', 'NBCC', 'GPPL', 'ADANIENT', 'RITES', 'AUROPHARMA', 'NTPC', 'SIEMENS', 'CROMPTON', 'INDIGO', 'ENGINERSIN', 'AIAENG', 'ATGL', 'TIMKEN', 'PATANJALI', 'MAHSEAMLES', 'JYOTHYLAB', 'NMDC', 'RKFORGE', 'APOLLOHOSP', 'CUMMINSIND', 'IRFC', 'HUDCO', 'EXIDEIND', 'INDHOTEL', 'RAINBOW', 'LICHSGFIN', 'PCBL', 'UPL', 'JKTYRE', 'JUBLINGREA', 'BHARATFORG', 'BAJAJ-AUTO', 'PRAJIND', 'JIOFIN', 'ETERNAL', 'JINDALSAW', 'LATENTVIEW', 'IPCALAB', 'FLUOROCHEM', 'NUVAMA', 'DRREDDY', 'ROUTE', 'WIPRO', 'CIPLA', 'DABUR', 'TBOTEK', 'BHARTIARTL', 'SKFINDIA', 'TATAINVEST', 'TRITURBINE', 'GNFC', 'MMTC', 'MANKIND', 'CGPOWER', 'EMAMILTD', 'SJVN', 'ALIVUS', 'VIJAYA', 'GODREJAGRO', 'BASF', 'TVSMOTOR', 'AADHARHFC', 'NESTLEIND', 'PGEL', 'NIVABUPA', 'AMBER', 'DLF', 'JPPOWER', 'BLUEDART', 'SUNDRMFAST', 'KAJARIACER', 'GLAXO', 'AARTIIND', 'HAPPSTMNDS', 'ADANIPORTS', 'NEULANDLAB', 'JSWSTEEL', 'ZYDUSLIFE', 'BERGEPAINT', 'NEWGEN', 'BOSCHLTD', 'ABBOTINDIA', 'FACT', 'LALPATHLAB', 'HCLTECH', 'DIXON', 'PAGEIND', 'EMCURE', 'NIACL', 'ESCORTS', 'STARHEALTH', 'VGUARD', 'NYKAA', 'LAURUSLABS', 'PHOENIXLTD', 'AJANTPHARM', 'MOTILALOFS', 'IGL', 'WOCKPHARMA', 'HINDUNILVR', 'OFSS', 'MGL', 'AWL', 'FORTIS', 'BAJAJHFL', 'COLPAL', 'NCC', 'ACC', 'RENUKA', 'CHALET', 'MAXHEALTH', 'POWERGRID', 'CENTURYPLY', 'SRF', 'BRIGADE', 'GAIL', 'CONCOR', 'TATAPOWER', 'MRF', 'PIDILITIND', 'TATAELXSI', 'GODREJIND', 'EICHERMOT', 'THERMAX', 'APLAPOLLO', 'BAYERCROP', 'SAIL', 'AAVAS', 'CEATLTD', 'ANANDRATHI', 'CARBORUNIV', 'KEC', 'PREMIERENE', 'ICICIPRULI', 'SAREGAMA', 'BALRAMCHIN', 'INOXWIND', 'FINPIPE', 'MOTHERSON', 'TECHNOE', 'AFCONS', 'SIGNATURE', 'GUJGASLTD', 'TATASTEEL', 'JUSTDIAL', 'SAMMAANCAP', 'POLYCAB', 'IKS', 'AKUMS', 'APOLLOTYRE', 'BHARTIHEXA', 'TTML', 'ERIS', 'CESC', 'ITC', 'HINDZINC', 'VOLTAS', 'TIINDIA', 'DIVISLAB', 'ARE&M', 'GSPL', 'RAYMOND', 'JUBLFOOD', 'ADANIGREEN', 'ALKEM', 'RCF', 'PVRINOX', 'RAYMONDLSL', 'LINDEINDIA', 'ASTERDM', 'PAYTM', 'JUBLPHARMA', 'HINDALCO', 'SYNGENE', 'JSWENERGY', 'SBILIFE', 'TATACOMM', 'TITAN', 'NSLNISP', '3MINDIA', 'ITI', 'BATAINDIA', 'GESHIP', 'CYIENT', 'BAJAJFINSV', 'RRKABEL', 'ADANIPOWER', 'KEI', 'GICRE', 'INDUSTOWER', 'KPIL', 'METROPOLIS', 'GMRAIRPORT', 'ZFCVINDIA', 'FIRSTCRY', 'NTPCGREEN', 'LEMONTREE', 'SHYAMMETL', 'HDFCLIFE', 'LUPIN', 'PPLPHARMA', 'HBLENGINE', 'BIKAJI', 'ADANIENSOL', 'POLICYBZR', 'INTELLECT', 'CCL', 'NAVA', 'VEDL', 'UNOMINDA', 'HONASA', 'VMM', 'HAVELLS', 'ASTRAL', 'WHIRLPOOL', 'JMFINANCIL', 'UBL', 'ACMESOLAR', 'USHAMART', 'SAPPHIRE', 'MARICO', 'OLAELEC', 'HOMEFIRST', 'ENDURANCE', 'ANANTRAJ', 'INDIAMART', 'HFCL', 'HINDCOPPER', 'NATIONALUM', 'CHENNPETRO', 'BIOCON', 'NLCINDIA', 'GLAND', 'APTUS', 'DEVYANI', 'MSUMI', 'BRITANNIA', 'MFSL', 'GLENMARK', 'GODFRYPHLP', 'KIMS', 'NHPC', 'ABCAPITAL', 'MASTEK', 'SUPREMEIND', 'IDEA', 'WELCORP', 'JINDALSTEL', 'ABSLAMC', 'ICICIGI', 'SYRMA', 'WESTLIFE', 'COHANCE', 'SARDAEN']
    #stock_list = ['JBMA', 'HINDCOPPER', 'GMDCLTD', 'GRSE', 'BEML', 'GPPL', 'COCHINSHIP', 'BDL', 'DATAPATTNS', 'MAZDOCK', 'NUVAMA', 'HFCL', 'SUPREMEIND', 'MOTHERSON', 'TRITURBINE', 'IDEA', 'ADANIPOWER', 'BEL', 'HAL', 'HINDZINC', 'OLECTRA', 'SOLARINDS', 'VEDL', 'TITAGARH', 'RAILTEL', 'GLAND', 'JINDALSAW', 'LUPIN', 'NEULANDLAB', 'FLUOROCHEM', 'INDUSTOWER', 'HBLENGINE', 'PNBHOUSING', 'POWERINDIA', 'NLCINDIA']
    stock_list = get_all_nse_stocks()
    for stock in stock_list:
        get_all_stock_data(stock)
        print("Data scraped for ", stock)

if __name__ == "__main__":
    main()
